import Sidebar from "@/components/Sidebar/Sidebar";
import "../globals.css";
import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MovieBox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={inter.className}>
      {children}
    </main>
  );
}
